before_install: cd src
language: csharp
solution: StingyJunk.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - ls
  - mono nuget.exe restore StingyJunk.sln